export enum ActionTypes {
  GET_TOKEN = 'GET_TOKEN',
  GET_ALBUM = 'GET_ALBUM',
  GET_SITE_MEDIA_COUNT = 'GET_SITE_MEDIA_COUNT',
  GET_ALBUM_LIST = 'GET_ALBUM_LIST',
  GET_USER_PROFILE = 'GET_USER_PROFILE'
}
