export enum MutationTypes {
  SET_TOKEN = 'SET_TOKEN',
  RESET_TOKEN = 'RESET_TOKEN',
  SET_ALBUM = 'SET_ALBUM',
  RESET_ALBUM = 'RESET_ALBUM',
  GET_SITE_MEDIA_COUNT = 'GET_SITE_MEDIA_COUNT',
  SET_SITE_MEDIA_COUNT = 'SET_SITE_MEDIA_COUNT',
  GET_ALBUM_LIST = 'GET_ALBUM_LIST',
  SET_ALBUM_LIST = 'SET_ALBUM_LIST',
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  SET_USER_PROFILE = 'SET_USER_PROFILE'
}
